### ISSUE TITLE
shvspy in Docker

### ISSUE THREAD

**Issue by robertobucher** [silicon-heaven/shvspy#17]
Hi
I'm trying  to integrate shvapp and shvspy into a Docker Image using the following commands in Dockerfile:

```
RUN mkdir SHV
WORKDIR SHV
RUN git clone https://github.com/silicon-heaven/shvapp
RUN git clone https://github.com/silicon-heaven/shvspy

WORKDIR shvapp
RUN git submodule update --init --recursive
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_INSTALL_PREFIX=.. ..
RUN make
RUN make install

WORKDIR /SHV/shvspy
RUN git submodule update --init --recursive
RUN mkdir build
WORKDIR build
RUN cmake -DCMAKE_INSTALL_PREFIX=.. ..
RUN make
RUN make install
```

My problem is related to the the shvspy application, because the admin password is not set in the "default-config.json" file and I have to set it in the container and then the container must be committed as new image.

I'd like to automatize the docker build with the correct password... It is possible to do this?

**Comment by fvacek** [comment]
I thing that we can change admin password in `default-config.json` to whatever what fix your image. Does it help you?

**Comment by robertobucher** [comment]
Thanks for your answer.
Setting the password in default-config.json doesn't work correctly. I put the right password in this file but in the shvspy application it doesn't fit what expected...

I solved the problem by copying the ./config/Elektroline/shvspy.conf from the docker container and installing it directly in the Dockerfile.

**Comment by fvacek** [comment]
It is IMO better solution, than adding any password to git repo. So can I close this issue or do you have still something to fix?

**Comment by robertobucher** [comment]
Yes, you can close this issue.
Thanks for your time!
Roberto

**Comment by fvacek** [comment]
You are welcome 
Fanda

**Comment by fvacek** [comment]
closing as resolved
