### ISSUE TITLE
Last git doesn't compile on Debian and Ubuntu

### ISSUE THREAD

**Issue by robertobucher** [silicon-heaven/shvspy#45]
Compiling of shvspy under Debian (and also probably Ubuntu) stops in both Qt5 and Qt6 by looking for 

include \<QStyledItemDelegate\>

Here the full error:

In file included from /home/bucher/sviluppo/GITHUB/LinuxLabo/SHV/shvspy/build/shvspy/shvspy_autogen/7KTMD75TS4/moc_accessitemdelegate.cpp:10,
                 from /home/bucher/sviluppo/GITHUB/LinuxLabo/SHV/shvspy/build/shvspy/shvspy_autogen/mocs_compilation.cpp:2:
/home/bucher/sviluppo/GITHUB/LinuxLabo/SHV/shvspy/build/shvspy/shvspy_autogen/7KTMD75TS4/../../../../shvspy/src/accessmodel/accessitemdelegate.h:4:10: fatal error: QStyledItemDelegate: No such file or directory
    4 | #include \<QStyledItemDelegate\>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [shvspy/CMakeFiles/shvspy.dir/build.make:118: shvspy/CMakeFiles/shvspy.dir/shvspy_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1198: shvspy/CMakeFiles/shvspy.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

The file QStyledItemDelegate is in my PC under

/usr/include/x86_64-linux-gnu/qt5/QtWidgets/QStyledItemDelegate
/usr/include/x86_64-linux-gnu/qt6/QtWidgets/QStyledItemDelegate

and I correctly have the folders:

/usr/lib/x86_64-linux-gnu/cmake/Qt6Widgets
/usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets

Roberto

**Comment by syyyr** [comment]
Please include the complete output of `make VERBOSE=1`.

**Comment by syyyr** [comment]
Also, what is the version of your OS?

**Comment by syyyr** [comment]
Please install the `qt6-tools` package, remove the build directory, and try again. It should hopefully solve your issue.

**Comment by robertobucher** [comment]
Thanks!

On Debian with:

qt6-tools-dev
qttools5-dev

compilation was OK again.

I think that the corresponding packages under Ubuntu are

qt6-tools-dev-tools
 qttools5-dev-tools
